---
title: "Curiobaby_Cooltower_analysis"
author: "Cameron Holdaway"
date: "1/30/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lme4)
library(lmerTest)
theme_set(theme_classic())
theme_update(# axis labels
  axis.title = element_text(size = 28),
  # tick labels
  axis.text = element_text(size = 24),
  # title 
  title = element_text(size = 24),
  legend.position = 'FALSE', 
  text = element_text(size=16), 
  element_line(size=1), 
  element_rect(size=2, color="#00000"))

primary_color = '#22AAAA'
secondary_color = '#252b31'
tertiary_color = '#c7cedf'
```

```{r}
df_rating = read_csv('curiotower_cooltower_raw_data_run_1.csv')
df_rating = df_rating %>% 
  filter(condition == 'interesting') %>% 
  select(towerID, button_pressed)
df_rating_avg = df_rating %>% 
  group_by(towerID) %>% 
  summarise(mu = mean(button_pressed),
            sd = sd(button_pressed),
            n = n(),
            std_err = sd/sqrt(n))

df_towers = read_csv('curiobaby-cooltower-annotations.csv')

df_towers$towerID = df_towers$SID
df_towers = df_towers %>%  
  select(towerID, height_tallest)
df_full = merge(df_rating_avg,df_towers,by=c("towerID"))
glimpse(df_full)
df_full$height_tallest[is.na(df_full$height_tallest)] <- 1
```

##Plot correlation of height and interestingness
```{r}
ggplot(data = df_full, aes(x = height_tallest, y = mu))+ 
  geom_point(color = primary_color, size = 2)+
  geom_smooth(method = 'lm', color = secondary_color)+
  ylab('interesting')+
  xlab('tower height')

```


