---
title: "curiotower_stability_tests"
author: "Cameron Holdaway"
date: "1/27/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lme4)
library(lmerTest)
theme_set(theme_classic())
theme_update(# axis labels
  axis.title = element_text(size = 28),
  # tick labels
  axis.text = element_text(size = 24),
  # title 
  title = element_text(size = 24),
  legend.position = 'FALSE', 
  text = element_text(size=16), 
  element_line(size=1), 
  element_rect(size=2, color="#00000"))
```

```{r, include = FALSE}
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
dat = read_csv('curiotower_raw_data_run_0.csv')
glimpse(dat)

tower_stable_avg = dat %>% 
  filter(condition == 'stable') %>% 
  group_by(towerID) %>% 
  summarise(avg_stable_rating = mean(button_pressed))

dat_interesting = dat %>% select('button_pressed',
                     'num_blocks',
                     'stability',
                     'viewpoint',
                     'towerID',
                     'prolificID', 
                     'condition') %>% 
  filter(condition== 'interesting')
dat_with_stability
dat_interesting$stability = factor(dat_interesting$stability, order = TRUE, 
                       levels = c('low', 'med', 'high'))
dat_interesting$jitter = dat_interesting$stability
dat_interesting$num_blocks_ordered = factor(dat_interesting$num_blocks, order = TRUE, 
                                levels = c('2', '4', '8'))


dat_full = merge(dat_interesting,tower_stable_avg,by=c("towerID"))
```


```{r, include=FALSE}

#add poke test a x-val information
df_stability_tests=read_csv('poke-test-stability-aspect-ratio.csv')
df_stability_tests$aspect_ratio = df_stability_tests$aspect_ratiomax
df_stability_tests$towerID= substr(df_stability_tests$towerID,
                                   1,
                                   nchar(df_stability_tests$towerID)-2)
glimpse(df_stability_tests)

dat_full$tower_id = substring(dat_full$towerID, 12,nchar(dat_full$towerID)-2)
#dat_full$tower_id = substr(dat_full$towerID,1,nchar(dat_full$towerID)-2)

dat_full = dat_full %>% 
  rename(
    tower_full_ID = towerID,
    towerID = tower_id
  )
glimpse(dat_full)
dat_with_stability = merge(dat_full,df_stability_tests,by=c("towerID"))

```

```{r}
glimpse(dat_with_stability)
```



## Compute lme results with experimental conditions

```{r}
#LME interestingness_rating ~ Jitter + Height + (1 | tower) + (1 | subjID)
model0 = lmer(button_pressed ~ 
                (1|towerID)+
                (1|prolificID),data=dat_full)
summary(model0)

model1 = lmer(button_pressed ~ 1 + 
                num_blocks+
                (1|towerID)+
                (1|prolificID),data=dat_full)

model2 = lmer(button_pressed ~ 1 + 
                num_blocks+
                stability + 
               (1|towerID)+
               (1|prolificID),data=dat_full)

model3 = lmer(button_pressed ~ 1 + 
                stability * 
                num_blocks +
                (1|towerID)+
                (1|prolificID),data=dat_full)

model4 = lmer(button_pressed ~ 1 + 
                stability *
                num_blocks +
                viewpoint+
                (1|towerID)+
                (1|prolificID),data=dat_full)

model5 = lmer(button_pressed ~ 1 + 
                stability *
                num_blocks *
                viewpoint+
                (1|towerID)+
                (1|prolificID),data=dat_full)

#anova(model0, model1, model2, model3, model4, model5)
```

## Compute lme results with physical properties (aspect ratio and dynamics)
```{r}
#Now create model
model_static = lmer(button_pressed ~ 1 + 
                aspect_ratio+
                (1|towerID)+
                (1|prolificID),data=dat_with_stability)

model_dynamic = lmer(button_pressed ~ 1 + 
                aspect_ratio+
                forcemin+
                (1|towerID)+
                (1|prolificID),data=dat_with_stability)

#anova(model_static, model_dynamic)

```

#Now add mean stability rating as first factor in best model
```{r}
model_stability_dynamics = lmer(button_pressed ~ 1 + 
                aspect_ratio+
                forcemin+
                avg_stable_rating+
                (1|towerID)+
                (1|prolificID),data=dat_with_stability)

model_stability= lmer(button_pressed ~ 1 + 
                avg_stable_rating+
                (1|towerID)+
                (1|prolificID),data=dat_with_stability)

#anova(model_stability, model_stability_dynamics)

#anova(model_dynamic, model_stability_dynamics)
```

#----Now run tests for explainable variance

```{r}

noise_ceiling = sqrt(0.977)
lm0 = lm(data = dat_with_stability, button_pressed ~ num_blocks)
lm1 = lm(data = dat_with_stability, button_pressed ~ jitter + num_blocks)
lm2 = lm(data = dat_with_stability, button_pressed ~ jitter * num_blocks)
lm3 = lm(data = dat_with_stability, button_pressed ~ jitter * num_blocks + viewpoint)
lm4 = lm(data = dat_with_stability, button_pressed ~ aspect_ratio)
lm5 = lm(data = dat_with_stability, button_pressed ~ num_blocks*aspect_ratio)
lm6 = lm(data = dat_with_stability, button_pressed ~ aspect_ratio +forcemin) 
lm7 = lm(data = dat_with_stability, button_pressed ~ aspect_ratio+ forcemin + avg_stable_rating)
lm8 = lm(data = dat_with_stability, button_pressed ~ avg_stable_rating)

lm_all = lm(data = dat_with_stability, button_pressed ~ aspect_ratio +forcemin + avg_stable_rating+ jitter * num_blocks)

summary(lm2)
summary(lm7)

#sqrt(summary(lm4)$r.squared)/noise_ceiling

```






